# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       meeftpserver

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    FTP Server
Version:    2.4
Release:    1
Group:      Qt/Qt
License:    LGPLv2.1
URL:        http://code.google.com/p/meeftpserver/
Source0:    %{name}-%{version}.tar.bz2
Source100:  meeftpserver.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   python >= 2.7
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10
BuildRequires:  desktop-file-utils

%description
FTP server to enable remote access to the file-system.

The FTP server makes a defined directory available with the FTP protocol. A FTP client running on another computer can connect with the FTP server and download, upload or delete files on the FTP server.

Password-protected read-write and/or anonymous read-only access are possible. FTP and SFTP (secure TLS/SSLv3 encryption) are supported. The server can be configured, started and stopped from a simple UI or via commandline.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}/server
%{_datadir}/%{name}/qml
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
/usr/bin
/usr/share/meeftpserver
/usr/share/applications
/usr/share/icons/hicolor/86x86/apps
# >> files
# << files
